// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC0hxvCVW4OwgLiTs523Z3fDyPbzV-IyTw',
    appId: '1:827435195551:web:2bb3d45ab879411d6f16aa',
    messagingSenderId: '827435195551',
    projectId: 'chowdeck-refix',
    authDomain: 'chowdeck-refix.firebaseapp.com',
    storageBucket: 'chowdeck-refix.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBsF6u6abFE-_0-olxpNwkVEF8QIaISgSY',
    appId: '1:827435195551:android:2b27351b840e7b7d6f16aa',
    messagingSenderId: '827435195551',
    projectId: 'chowdeck-refix',
    storageBucket: 'chowdeck-refix.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBWvFgITMN1iv1hwbst3S7uduir6lM_y6w',
    appId: '1:827435195551:ios:9ac2232eb17321116f16aa',
    messagingSenderId: '827435195551',
    projectId: 'chowdeck-refix',
    storageBucket: 'chowdeck-refix.firebasestorage.app',
    iosBundleId: 'com.example.chowDeckRefix',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC0hxvCVW4OwgLiTs523Z3fDyPbzV-IyTw',
    appId: '1:827435195551:web:f68b0c85b44dee536f16aa',
    messagingSenderId: '827435195551',
    projectId: 'chowdeck-refix',
    authDomain: 'chowdeck-refix.firebaseapp.com',
    storageBucket: 'chowdeck-refix.firebasestorage.app',
  );
}
